### ISSUE TITLE
Dependabot PR are a bit inconsistent for our tooling/process

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf#82]
### Is your feature request related to a problem? Please describe.

Mostly (or all) PR tests fails
https://github.com/vmware/repository-service-tuf-cli/actions/runs/3286749761/jobs/5415187329

The dependabot changes don't follow our current process

Current process is quite simple
```shell 
pipenv shell
pipenv update -d
make requirements
```

Run local tests

```
tox -r
```

### Describe the solution you'd like

All ideas below are just a seed, no elaboration was done

Suggestion
1) Customize the dependabot action to run our process
2) Dependabot opens a issue only?

**Comment by rdimitrov** [comment]
After discussing with @kairoaraujo the details around how rstuf repositories are configured (using both pipfile and requirements files), we decided it would be best to disable dependabot for python dependencies because of the up-mentioned concerns and instead use a daily cron job that handles the dependency updates but also rebuilds the requirements files (steps from above). 

Reference issue for creating a cron job - https://github.com/vmware/repository-service-tuf/issues/84

**Comment by rdimitrov** [comment]
Closed by completing #86 and #84
